# yaml-language-server: $schema=https://raw.githubusercontent.com/kjanat/github-labelmanager/master/.github/labels.schema.json
---
labels:
  # Type labels
  - name: bug
    color: "#d73a4a"
    description: Something isn't working

  - name: feature
    color: "#a2eeef"
    description: New feature or request
    aliases: [enhancement]

  - name: docs
    color: "#0075ca"
    description: Documentation improvements
    aliases: [documentation]

  - name: refactor
    color: "#fbca04"
    description: Code refactoring without functionality changes

  - name: performance
    color: "#5319e7"
    description: Performance improvements

  - name: testing
    color: "#fbca04"
    description: Test-related changes

  - name: dependencies
    color: "#0366d6"
    description: Dependency updates

  - name: breaking
    color: "#b60205"
    description: Breaking changes

  # Priority labels
  - name: "priority: critical"
    color: "#b60205"
    description: Must be fixed ASAP

  - name: "priority: high"
    color: "#d93f0b"
    description: High priority issue

  - name: "priority: medium"
    color: "#fbca04"
    description: Medium priority issue

  - name: "priority: low"
    color: "#0e8a16"
    description: Low priority issue

  # Status labels
  - name: "status: blocked"
    color: "#000000"
    description: Blocked by another issue or external factor

  - name: "status: needs-info"
    color: "#cfd3d7"
    description: Needs more information from reporter

  - name: "status: wontfix"
    color: "#ffffff"
    description: This will not be worked on

  # Component labels
  - name: "component: cli"
    color: "#1d76db"
    description: Related to CLI interface

  - name: "component: export"
    color: "#1d76db"
    description: Related to GLB/glTF export

  - name: "component: analysis"
    color: "#1d76db"
    description: Related to mesh/bone analysis

  - name: "component: textures"
    color: "#1d76db"
    description: Related to texture processing

  - name: "component: cleaners"
    color: "#1d76db"
    description: Related to mesh/bone/UV cleaners

  - name: "component: wasm"
    color: "#1d76db"
    description: Related to WASM/wasmtime integration

  - name: "component: blender"
    color: "#1d76db"
    description: Related to Blender/bpy integration

  - name: "component: gltfpack"
    color: "#1d76db"
    description: Related to gltfpack integration

  - name: "component: compression"
    color: "#1d76db"
    description: Related to Draco/mesh compression

  # Infrastructure labels
  - name: "infra: docker"
    color: "#0e8a16"
    description: Related to Docker/containerization

  - name: "infra: ci"
    color: "#0e8a16"
    description: Related to CI/CD workflows

  - name: "infra: pypi"
    color: "#0e8a16"
    description: Related to PyPI packaging/publishing

  # Misc labels
  - name: good first issue
    color: "#7057ff"
    description: Good for newcomers

  - name: help wanted
    color: "#008672"
    description: Extra attention is needed

  - name: duplicate
    color: "#cfd3d7"
    description: This issue or PR already exists

  - name: invalid
    color: "#e4e669"
    description: This doesn't seem right

delete:
  - question
