# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
---
issue_enrichment:
  auto_enrich: { enabled: true }
  labeling:
    auto_apply_labels: true
    labeling_instructions:
      # Type labels
      - { label: bug, instructions: something isn't working }
      - { label: feature, instructions: new feature or request }
      - { label: docs, instructions: documentation improvements }
      - { label: refactor, instructions: code refactoring without functionality changes }
      - { label: performance, instructions: performance improvements }
      - { label: testing, instructions: test-related changes }
      - { label: dependencies, instructions: dependency updates }
      - { label: breaking, instructions: breaking changes }
      # Priority labels
      - { label: "priority: critical", instructions: issue must be fixed ASAP }
      - { label: "priority: high", instructions: high priority issues }
      - { label: "priority: medium", instructions: medium priority issues }
      - { label: "priority: low", instructions: low priority issues }
      # Status labels
      - { label: "status: blocked", instructions: blocked by another issue or external factor }
      - { label: "status: needs-info", instructions: needs more information from reporter }
      - { label: "status: wontfix", instructions: this will not be worked on }
      # Component labels
      - { label: "component: cli", instructions: related to CLI interface }
      - { label: "component: export", instructions: related to GLB/glTF export }
      - { label: "component: analysis", instructions: related to mesh/bone analysis }
      - { label: "component: textures", instructions: related to texture processing }
      - { label: "component: cleaners", instructions: related to mesh/bone/UV cleaners }
      - { label: "component: wasm", instructions: related to WASM/wasmtime integration }
      - { label: "component: blender", instructions: related to Blender/bpy integration }
      - { label: "component: gltfpack", instructions: related to gltfpack integration }
      - { label: "component: compression", instructions: related to Draco/mesh compression }
      # Infrastructure labels
      - { label: "infra: docker", instructions: related to Docker/containerization }
      - { label: "infra: ci", instructions: related to CI/CD workflows }
      - { label: "infra: pypi", instructions: related to PyPI packaging/publishing }
      # Misc labels
      - { label: good first issue, instructions: issues good for newcomers }
      - { label: help wanted, instructions: extra attention is needed }
      - { label: duplicate, instructions: issue or PR already exists }
      - { label: invalid, instructions: this doesn't seem right }
