# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
---
name: Download WASM
description: Download latest gltfpack WASM from npm

inputs:
  version:
    description: "Specific version to download, e.g. 1.0.0 (default: latest)"
    required: false
    default: ""

outputs:
  before:
    description: WASM version before download
    value: ${{ steps.download.outputs.before }}
  after:
    description: WASM version after download
    value: ${{ steps.download.outputs.after }}
  uv-available:
    description: Whether uv was already available
    value: ${{ steps.check-uv.outputs.uv-available }}

runs:
  using: composite
  steps:
    - name: Check if uv is available
      id: check-uv
      shell: bash
      env: { ACTION_PATH: "${{ github.action_path }}" }
      run: "${ACTION_PATH}/uv-available.sh | tee ${GITHUB_OUTPUT}"
    - name: Install uv
      if: steps.check-uv.outputs.uv-available == 'false'
      uses: astral-sh/setup-uv@v7
    - name: Download latest WASM from npm
      id: download
      shell: bash
      env: { WASM_VERSION: "${{ inputs.version }}", ACTION_PATH: "${{ github.action_path }}" }
      run: "${ACTION_PATH}/download.sh"
