# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: autofix.ci
on: { push: { branches: ["master"] }, pull_request: {}, workflow_call: {}, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 1 }
      - uses: kjanat/runner@v0.12.1
      - uses: kjanat/install-dprint@v1
      - uses: ./.github/actions/install-uv
      - uses: taiki-e/install-action@just

      - run: runner install docs

      - run: uvx ruff check --fix-only
      - run: dprint fmt --allow-no-files --diff --excludes .github

      - if: github.event_name != 'pull_request'
        run: dprint config update --yes --recursive

      - uses: autofix-ci/action@v1
